Added footer to app. Also Added logo svg for navbar.
Sosobo-code/next-cws pull request #6
Opened 2024-10-05 09:43 UTC by Sosobo-code

2024-10-05 10:03 UTC, Crystallized21 requested changes

2024-10-05 10:03 UTC, Crystallized21 commented on src/app/page.tsx
> +
Remove this unnecessary space

2024-10-05 10:03 UTC, Crystallized21 commented on src/components/Footer.tsx
> +        <div className="text-center p-3 bg-primary text-white">
Change `bg-primary` to `bg-background` so shadcn can recognise light and dark mode

2024-10-05 10:03 UTC, Crystallized21 commented on src/components/HomePage.tsx
> +
???

2024-10-05 10:03 UTC, Crystallized21 commented on src/components/NavBar.tsx
> +
Unnecessary empty lines

2024-10-05 10:04 UTC, Sosobo-code commented on src/components/NavBar.tsx
> +
mb

2024-10-06 08:24 UTC, Crystallized21 requested changes
bruh

2024-10-06 08:24 UTC, Crystallized21 commented on src/components/Footer.tsx
> +    <div className="text-center p-3 bg-primary text-white">
`bg-background` to match shadcn themes

2024-10-06 08:26 UTC, Crystallized21 approved these changes
lgtm

2024-10-06 08:27 UTC, merged