color-picker
Sosobo-code/next-cws pull request #9
Opened 2024-10-17 00:34 UTC by Sosobo-code

2024-10-17 00:51 UTC, Crystallized21 requested changes

2024-10-17 00:51 UTC, Crystallized21 commented on src/components/NavBar.tsx
> +                      <Link href="/store/wraps">
If your just using `/store/wraps`, rework the routing to just be `/wraps`

2024-10-17 00:51 UTC, Crystallized21 commented on src/components/NavBar.tsx
>                        <Link href="/">
This isn't used, this will still appear in the navbar. You only deleted the ListItem but not the link itself.

2024-10-17 00:51 UTC, Crystallized21 commented on src/components/NavBar.tsx
>                        </Link>
This routing does not go anywhere, this conflicts with the `NavBarMobile.tsx` where there is `href="/services"` how about `/about`?

2024-10-17 00:51 UTC, Crystallized21 commented on src/components/NavBarMobile.tsx
>                  </ListItem>
As above.

2024-10-17 00:57 UTC, Crystallized21 commented
By the way, have more descriptive titles and descriptions please. 🚀

2024-10-17 01:12 UTC, Crystallized21 approved these changes
sure

2024-11-23 10:56 UTC, Sosobo-code reviewed
ok bro

2024-11-23 10:56 UTC, merged